---
- hosts: all
  tasks:
   - name: Ensiring that podman is in the system
     block:
      - name: Installing Podman on the host
        package:
          name: podman
          state: present
      - name: Pulling Grafana from the registry
        podman_registry:
          name: docker.io/influxdb:latest
      - name: Starting Podman Image
        podm

