---
- hosts: all
  tasks:
   - name: Add Telegraf Repository
     yum_repository:
      name: influxdb
      baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
      gpgcheck: yes
      enabled: yes
      gpgkey: https://repos.influxdata.com/influxdb.key
      description: influxdb
   - name: Install telegraf package
     package:
      name: telegraf
      state: present

#### Setting up telegraf config for Linux systems
   
   - name: Copying configuration and customizing it
     template:
      src: telegraf.j2
      dest: /etc/telegraf/telegraf.conf
     notify: Restart telegraf service
   - name: Enable Telegraf Service
     service:
      name: telegraf
      state: started

  handlers: 
    - name: Restart telegraf service
      service:
        name: telegraf
        state: restarted

      

