---
- hosts: winsrv
  gather_facts: true
  tasks:
    - name: Install IIS with sub features and management tools
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: yes
        include_management_tools: yes
      tags: iis_install

    - name: install critical updates except blacklisted
      win_updates:
        category_names: CriticalUpdates
        reboot: no 
        blacklist:
        - KB4056892
      tags: win_upgrade
    - name: ensure IIS is running
      win_service:
        name: W3Svc	
        state: started
      tags: iis_running


